#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

set -e

echo "=== build ==="

VIRTENV="${OPENSHIFT_PYTHON_DIR}/virtenv/"
export PYTHON_EGG_CACHE="${VIRTENV}/lib/python2.6/site-packages"
source "${VIRTENV}/bin/activate"

pushd "${OPENSHIFT_REPO_DIR}"
python setup.py develop
easy_install SAUCE[lti]
popd

for dir in libs wsgi; do
        [[ -d "${OPENSHIFT_REPO_DIR}/${dir}" ]] || echo "Creating directory /${dir}" && mkdir "${OPENSHIFT_REPO_DIR}/${dir}"
done

echo "Copying /wsgi/application"
cp "${OPENSHIFT_REPO_DIR}/.openshift/files/application" "${OPENSHIFT_REPO_DIR}/wsgi/application"
echo "Copying /production.ini"
#cp "${OPENSHIFT_REPO_DIR}/.openshift/files/production.ini" "${OPENSHIFT_REPO_DIR}/production.ini"
cp "${OPENSHIFT_REPO_DIR}/production.ini.tmpl" "${OPENSHIFT_REPO_DIR}/production.ini"

echo "Symlinking /data"
ln -s "${OPENSHIFT_DATA_DIR}" "${OPENSHIFT_REPO_DIR}/data"
echo "Symlinking /sauce/public"
ln -s "${OPENSHIFT_REPO_DIR}/wsgi/static" "${OPENSHIFT_REPO_DIR}/sauce/public"

echo "Configuring production.ini"
if [[ -n "${OPENSHIFT_POSTGRESQL_DB_URL}" ]]; then
	easy_install psycopg2
        sed -i "${OPENSHIFT_REPO_DIR}/production.ini"  -e "s|^sqlalchemy.url.*$|sqlalchemy.url = ${OPENSHIFT_POSTGRESQL_DB_URL}${OPENSHIFT_APP_NAME}|g"
elif [[ -n "${OPENSHIFT_MYSQL_DB_URL}" ]]; then
	easy_install mysql-python
        sed -i "${OPENSHIFT_REPO_DIR}/production.ini" -e "s|^sqlalchemy.url.*$|sqlalchemy.url = ${OPENSHIFT_MYSQL_DB_URL}${OPENSHIFT_APP_NAME}|g"
fi

sed -i "${OPENSHIFT_REPO_DIR}/production.ini" -e "s|^app_instance_uuid.*$|app_instance_uuid = ${OPENSHIFT_GEAR_UUID}|g"
sed -i "${OPENSHIFT_REPO_DIR}/production.ini" -e "s|^cookie_secret.*$|cookie_secret = $(uuidgen)|g"
sed -i "${OPENSHIFT_REPO_DIR}/production.ini" -e "s|^beaker\.session\.secret.*$|beaker\.session\.secret = $(uuidgen)|g"
sed -i "${OPENSHIFT_REPO_DIR}/production.ini" -e "s|^beaker\.session\.validate_key.*$|beaker\.session\.validate_key = $(uuidgen)|g"
sed -i "${OPENSHIFT_REPO_DIR}/production.ini" -e "s|^cache_dir.*|cache_dir = ${OPENSHIFT_DATA_DIR}/|g" 
sed -i "${OPENSHIFT_REPO_DIR}/production.ini" -e "s|^templating\.mako\.compiled_templates_dir.*|templating\.mako\.compiled_templates_dir = ${OPENSHIFT_DATA_DIR}/templates/|g" 
