#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

echo "=== deploy ==="

VIRTENV="${OPENSHIFT_PYTHON_DIR}/virtenv/"
export PYTHON_EGG_CACHE="${VIRTENV}/lib/python2.6/site-packages"
source "${VIRTENV}/bin/activate"

if [[ ! -e "${OPENSHIFT_DATA_DIR}/DB_INITIALIZED" ]]; then
	echo "Initializing database"
	pushd "${OPENSHIFT_REPO_DIR}"
	paster setup-app "${OPENSHIFT_REPO_DIR}/production.ini"
	popd
	touch "${OPENSHIFT_DATA_DIR}/DB_INITIALIZED"
fi

pushd "${OPENSHIFT_REPO_DIR}"
echo "Upgrading database"
./alembic "${OPENSHIFT_REPO_DIR}/production.ini" upgrade head
popd
