"""submission_uuid

Revision ID: 1ef71349299d
Revises: 1e52c8ddf5a0
Create Date: 2015-08-31 19:17:59.932718

"""
#
# # SAUCE - System for AUtomated Code Evaluation
# # Copyright (C) 2013 Moritz Schlarb
# #
# # This program is free software: you can redistribute it and/or modify
# # it under the terms of the GNU Affero General Public License as published by
# # the Free Software Foundation, either version 3 of the License, or
# # any later version.
# #
# # This program is distributed in the hope that it will be useful,
# # but WITHOUT ANY WARRANTY; without even the implied warranty of
# # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# # GNU Affero General Public License for more details.
# #
# # You should have received a copy of the GNU Affero General Public License
# # along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# revision identifiers, used by Alembic.
revision = '1ef71349299d'
down_revision = '1e52c8ddf5a0'

from alembic import op
#from alembic.operations import Operations as op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType))
    op.create_index(op.f('ix_submissions_uuid'), 'submissions', ['uuid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_uuid'), table_name='submissions')
    op.drop_column('submissions', 'uuid')
    ### end Alembic commands ###
